import { siteDetails } from '../data/siteDetails'

type LegalPageProps = { type: 'privacy' | 'terms' }

const LegalPage = ({ type }: LegalPageProps) => {
  const privacy = type === 'privacy'
  return (
    <article className="rounded-2xl bg-white/45 p-7 shadow-soft ring-1 ring-neutral-200/50 md:p-12">
      <p className="text-xs uppercase tracking-[0.2em] text-neutral-500">Stilte &amp; Draad · {siteDetails.legalEntity}</p>
      <h1 className="mt-3 text-2xl font-semibold uppercase tracking-[0.16em]">{privacy ? 'Privacyverklaring' : 'Algemene voorwaarden'}</h1>
      <p className="mt-3 text-xs text-neutral-500">Laatst bijgewerkt: 9 augustus 2026</p>
      <div className="mt-8 space-y-7 text-sm leading-7 text-neutral-700">
        {privacy ? <>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Wie verantwoordelijk is</h2><p className="mt-2">{siteDetails.legalOwner}, handelend onder {siteDetails.legalEntity} met het project {siteDetails.name}, is verantwoordelijk voor de verwerking van persoonsgegevens via deze website. {siteDetails.maker} is de creatieve maker en verteller. Je bereikt ons via <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Welke gegevens we verwerken</h2><p className="mt-2">Bij contact verwerken we de gegevens die je zelf meestuurt. Voor een bestelling verwerken we naam, e-mailadres, eventueel telefoonnummer, bezorgadres, gekozen werken, afhaal- of verzendkeuze en een optioneel bericht. Voor een donatie verwerken we bedrag en e-mailadres en, tenzij je anoniem doneert, je naam. Bij een herroeping verwerken we bestelnummer, e-mailadres, omvang van de herroeping en eventueel de omschrijving van het betreffende werk.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Waarom en op welke grondslag</h2><div className="mt-2 space-y-2"><p>We verwerken gegevens om een overeenkomst uit te voeren of voorbereidingen daarvoor te treffen, bijvoorbeeld bij bestellen, afhalen, bezorgen en retourneren. Administratieve gegevens bewaren we waar dat nodig is om aan wettelijke verplichtingen te voldoen. Beveiliging, fraudepreventie en het beantwoorden van algemene vragen kunnen berusten op een gerechtvaardigd belang. Als toestemming wettelijk nodig is, vragen we die vooraf en kun je haar weer intrekken.</p><p>We gebruiken jouw gegevens niet voor ongevraagde commerciële e-mail en nemen geen uitsluitend geautomatiseerde besluiten met rechtsgevolgen.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Betaling en dienstverleners</h2><p className="mt-2">Mollie verwerkt de noodzakelijke betaalgegevens voor bestellingen en donaties. Wij ontvangen geen volledige bank- of kaartgegevens, maar een betaalreferentie en geverifieerde status. Vercel verzorgt hosting en serverfuncties, Neon de database en Resend de transactionele e-mails. Een bezorgpartij ontvangt bij verzending alleen de gegevens die nodig zijn om de bestelling te bezorgen. Deze partijen verwerken gegevens uitsluitend voor hun taak en volgens de toepasselijke afspraken en beveiligingsmaatregelen.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Bewaartermijnen</h2><div className="mt-2 space-y-2"><p>Fiscale basisgegevens uit de verkoop- en financiële administratie bewaren we in beginsel zeven jaar. Een onbeantwoorde algemene contactvraag verwijderen we uiterlijk twee jaar na het laatste contact, tenzij langer bewaren nodig is voor een lopende afspraak of juridisch geschil. Technische beveiligings- en rate-limitgegevens bewaren we zo kort mogelijk.</p><p>Gegevens in de e-mailwachtrij worden alleen gebruikt voor transactionele berichten. Zodra een bericht definitief is verwerkt, bewaren we uitsluitend wat nodig is om verzending en eventuele fouten te kunnen aantonen.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Jouw privacyrechten</h2><p className="mt-2">Je kunt vragen om inzage, correctie, verwijdering, beperking, overdracht of bezwaar. Je kunt een toestemming intrekken. Mail je verzoek naar <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. We kunnen om aanvullende informatie vragen om je identiteit veilig vast te stellen. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Cookies en browseropslag</h2><p className="mt-2">Er worden momenteel geen advertentie- of analysecookies geplaatst. Functionele browseropslag onthoudt alleen winkelmand, favorieten en je cookievoorkeur. De versiegebonden cookievoorkeur blijft maximaal zes maanden bewaard en wordt daarna opnieuw gevraagd. Via “Cookievoorkeuren” onderaan iedere pagina kun je jouw keuze eerder opnieuw openen en wijzigen.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Beveiliging, wijzigingen en contact</h2><p className="mt-2">We treffen passende technische en organisatorische maatregelen en beperken toegang tot mensen en partijen die deze nodig hebben. Deze verklaring kan veranderen wanneer de website of wetgeving verandert; de datum bovenaan laat zien wanneer de tekst voor het laatst is bijgewerkt.</p><p className="mt-2">{siteDetails.legalOwner} · {siteDetails.legalEntity} · project {siteDetails.name}<br />KvK {siteDetails.chamberOfCommerce} · btw-ID {siteDetails.vatNumber}<br />{siteDetails.address.street}, {siteDetails.address.postalCode} {siteDetails.address.city}, {siteDetails.address.country}<br /><a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a></p></section>
        </> : <>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Ondernemer en toepasselijkheid</h2><p className="mt-2">Deze voorwaarden gelden voor online aanbiedingen en overeenkomsten tussen een consument en {siteDetails.legalOwner}, eenmanszaak {siteDetails.legalEntity}, voor het project {siteDetails.name}, gevestigd aan {siteDetails.address.street}, {siteDetails.address.postalCode} {siteDetails.address.city}, {siteDetails.address.country}, KvK {siteDetails.chamberOfCommerce}, btw-ID {siteDetails.vatNumber}, e-mail <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. {siteDetails.maker} is de creatieve maker en verteller van de aangeboden werken. Afwijkende afspraken gelden alleen als die schriftelijk zijn bevestigd.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Aanbod en overeenkomst</h2><p className="mt-2">Bij ieder bestelbaar werk vermelden we de belangrijkste kenmerken, consumentenprijs, beschikbaarheid en ontvangstopties. Kennelijke vergissingen binden ons niet. De overeenkomst ontstaat wanneer de bestelling elektronisch is bevestigd, onder voorbehoud van een aantoonbaar voorraadconflict. In dat uitzonderlijke geval blokkeren we automatische voorraadtoewijzing, nemen we persoonlijk contact op en herstellen we de betaling waar nodig.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Handgemaakt en uniek</h2><p className="mt-2">De werken worden met de hand gemaakt. Kleine onregelmatigheden, sporen van het materiaal en beperkte kleurverschillen horen bij hun karakter. Kleuren kunnen per beeldscherm afwijken. Zulke natuurlijke verschillen doen niets af aan de wettelijke rechten wanneer een werk niet aan de overeenkomst beantwoordt.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Productafbeeldingen</h2><p className="mt-2">De afgebeelde handgemaakte werken worden waarheidsgetrouw weergegeven. Voor een rustige en samenhangende presentatie kunnen achtergronden, omgevingen en uitsneden digitaal of met AI zijn bewerkt. Het aangeboden werk zelf wordt daarbij niet digitaal veranderd. Een weergegeven omgeving dient uitsluitend ter sfeer en is niet maatgevend voor de afmetingen van het werk. Kleuren kunnen door beeldscherminstellingen beperkt afwijken.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Het eigen verhaal bij het werk</h2><p className="mt-2">Ieder aangeschaft werk wordt fysiek geleverd met de eigen bijbehorende tekst van Jannie: een quote, verhaal, gedicht of spoken-wordtekst die uit het werk, haar herinneringen en haar leven is voortgekomen. Deze bestaande tekst hoort inhoudelijk bij het werk en wordt niet op maat voor de koper geschreven.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Prijzen en betaling</h2><p className="mt-2">Prijzen worden in euro vermeld als het definitieve bedrag dat de consument voor het werk betaalt; bij het afrekenen wordt geen extra btw boven op de getoonde productprijs gezet. Verzendkosten worden afzonderlijk getoond. Betalingen en donaties worden veilig verwerkt door Mollie. Btw-ID van de verkoper: {siteDetails.vatNumber}.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Afhalen en levering</h2><div className="mt-2 space-y-2"><p>Je kunt gratis afhalen op afspraak in IJzendoorn. Dit is een afhaallocatie en niet het juridische vestigingsadres. We nemen na een bevestigde bestelling persoonlijk contact op; afhalen is doorgaans mogelijk binnen twee tot vijf werkdagen. Het volledige afhaaladres delen we bij het maken van de afspraak.</p><p>Verzending binnen Nederland kost €6,95 per volledige bestelling, ongeacht het aantal of formaat van de gekozen werken. We gebruiken het in de bestelling opgegeven Nederlandse bezorgadres. Als een afgesproken termijn niet haalbaar blijkt, informeren we de koper zo snel mogelijk en blijven de wettelijke rechten bij te late levering gelden.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Bedenktijd en retourneren</h2><div className="mt-2 space-y-2"><p>Bij een online aankoop heeft een consument in beginsel veertien dagen bedenktijd vanaf de dag na ontvangst. Binnen die termijn kan de overeenkomst zonder reden worden herroepen via de <a className="underline underline-offset-4" href="/herroepen">digitale herroepingsfunctie</a> of via <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}?subject=Herroeping%20bestelling`}>{siteDetails.email}</a>.</p><p>Na de herroeping moet het werk binnen veertien dagen worden teruggebracht of zorgvuldig worden teruggestuurd naar het bovenstaande Nederlandse adres. De rechtstreekse retourkosten zijn voor de koper als vooraf duidelijk is gemaakt wat die wijze van retourneren kost. Gebruik en verpakking mogen niet verder gaan dan nodig is om aard, kenmerken en werking te beoordelen; aantoonbare waardevermindering door verdergaand gebruik kan worden verrekend.</p><p>Bij volledige herroeping betalen we het aankoopbedrag en de kosten van de goedkoopste aangeboden standaardlevering binnen veertien dagen terug via hetzelfde betaalmiddel. We mogen wachten totdat het werk is ontvangen of bewijs van terugzending is geleverd. Bij gedeeltelijke herroeping worden oorspronkelijke leveringskosten niet terugbetaald.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Conformiteit en klachten</h2><div className="mt-2 space-y-2"><p>Een werk moet beantwoorden aan wat de koper op grond van de overeenkomst redelijkerwijs mag verwachten. Wettelijke garantierechten worden niet beperkt door deze voorwaarden.</p><p>Een klacht kan met bestelnummer en een duidelijke omschrijving worden gestuurd naar <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. We bevestigen ontvangst en streven ernaar binnen veertien dagen inhoudelijk te reageren. Als meer tijd nodig is, laten we binnen die termijn weten wanneer een antwoord volgt.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Aansprakelijkheid en recht</h2><p className="mt-2">Niets in deze voorwaarden sluit aansprakelijkheid uit die volgens dwingend consumentenrecht niet mag worden uitgesloten. Op de overeenkomst is Nederlands recht van toepassing. Een consument behoudt de bescherming van dwingend recht van het land waar die woont. Geschillen kunnen worden voorgelegd aan de bevoegde rechter.</p></section>
        </>}
      </div>
    </article>
  )
}

export default LegalPage
