import { siteDetails } from '../data/siteDetails'

type LegalPageProps = { type: 'privacy' | 'terms' }

const LegalPage = ({ type }: LegalPageProps) => {
  const privacy = type === 'privacy'
  return (
    <article className="rounded-2xl bg-white/45 p-7 shadow-soft ring-1 ring-neutral-200/50 md:p-12">
      <p className="text-xs uppercase tracking-[0.2em] text-neutral-500">Concept · laat dit vóór de winkelopening juridisch controleren</p>
      <h1 className="mt-3 text-2xl font-semibold uppercase tracking-[0.16em]">{privacy ? 'Privacyverklaring' : 'Algemene voorwaarden'}</h1>
      <p className="mt-3 text-xs text-neutral-500">Laatst bijgewerkt: 1 augustus 2026</p>
      <div className="mt-8 space-y-7 text-sm leading-7 text-neutral-700">
        {privacy ? <>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Wie verantwoordelijk is</h2><p className="mt-2">{siteDetails.name}, door {siteDetails.owner}, is verantwoordelijk voor de verwerking van persoonsgegevens via deze website. Je bereikt ons via <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. De volledige contact- en adresgegevens staan onderaan deze verklaring.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Welke gegevens we verwerken</h2><p className="mt-2">Bij contact verwerken we de gegevens die je zelf meestuurt. Voor een bestelling verwerken we naam, e-mailadres, eventueel telefoonnummer, bezorgadres, gekozen werken, afhaal- of verzendkeuze en een optioneel bericht. Voor een donatie verwerken we bedrag en e-mailadres en, tenzij je anoniem doneert, je naam. Bij een herroeping verwerken we bestelnummer, e-mailadres, omvang van de herroeping en eventueel de omschrijving van het betreffende werk.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Waarom en op welke grondslag</h2><div className="mt-2 space-y-2"><p>We verwerken gegevens om een overeenkomst uit te voeren of voorbereidingen daarvoor te treffen, bijvoorbeeld bij bestellen, afhalen, bezorgen en retourneren. Administratieve gegevens bewaren we waar dat nodig is om aan wettelijke verplichtingen te voldoen. Beveiliging, fraudepreventie en het beantwoorden van algemene vragen kunnen berusten op een gerechtvaardigd belang. Als toestemming wettelijk nodig is, vragen we die vooraf en kun je haar weer intrekken.</p><p>We gebruiken jouw gegevens niet voor ongevraagde commerciële e-mail en nemen geen uitsluitend geautomatiseerde besluiten met rechtsgevolgen.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Betaling en dienstverleners</h2><p className="mt-2">Online betalen en doneren zijn momenteel uitgeschakeld. Als deze functies later worden geopend, verwerkt de gekozen betaaldienstverlener de noodzakelijke betaalgegevens. Stilte &amp; Draad ontvangt geen volledige bank- of kaartgegevens, maar alleen een betaalreferentie en geverifieerde status. Hosting-, database-, e-mail- en bezorgpartijen krijgen alleen toegang voor zover dat noodzakelijk is voor hun taak en op basis van passende afspraken.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Bewaartermijnen</h2><div className="mt-2 space-y-2"><p>Fiscale basisgegevens uit de verkoop- en financiële administratie bewaren we in beginsel zeven jaar. Een onbeantwoorde algemene contactvraag verwijderen we uiterlijk twee jaar na het laatste contact, tenzij langer bewaren nodig is voor een lopende afspraak of juridisch geschil. Technische beveiligings- en rate-limitgegevens bewaren we zo kort mogelijk.</p><p>Gegevens in de e-mailwachtrij worden alleen gebruikt voor transactionele berichten. Zodra een bericht definitief is verwerkt, bewaren we uitsluitend wat nodig is om verzending en eventuele fouten te kunnen aantonen.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Jouw privacyrechten</h2><p className="mt-2">Je kunt vragen om inzage, correctie, verwijdering, beperking, overdracht of bezwaar. Je kunt een toestemming intrekken. Mail je verzoek naar <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. We kunnen om aanvullende informatie vragen om je identiteit veilig vast te stellen. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Cookies en browseropslag</h2><p className="mt-2">Er worden momenteel geen advertentie- of analysecookies geplaatst. Functionele browseropslag onthoudt alleen winkelmand, favorieten en je cookievoorkeur. Via “Cookievoorkeuren” onderaan iedere pagina kun je jouw keuze opnieuw openen.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Beveiliging, wijzigingen en contact</h2><p className="mt-2">We treffen passende technische en organisatorische maatregelen en beperken toegang tot mensen en partijen die deze nodig hebben. Deze verklaring kan veranderen wanneer de website of wetgeving verandert; de datum bovenaan laat zien wanneer de tekst voor het laatst is bijgewerkt.</p><p className="mt-2">{siteDetails.name} · {siteDetails.owner} · KvK {siteDetails.chamberOfCommerce}<br />{siteDetails.address.street}, {siteDetails.address.postalCode} {siteDetails.address.city}, {siteDetails.address.country}<br /><a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a></p></section>
        </> : <>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Ondernemer en toepasselijkheid</h2><p className="mt-2">Deze voorwaarden gelden voor online aanbiedingen en overeenkomsten tussen een consument en {siteDetails.name}, door {siteDetails.owner}, gevestigd aan {siteDetails.address.street}, {siteDetails.address.postalCode} {siteDetails.address.city}, {siteDetails.address.country}, KvK {siteDetails.chamberOfCommerce}, e-mail <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. Afwijkende afspraken gelden alleen als die schriftelijk zijn bevestigd.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Aanbod en overeenkomst</h2><p className="mt-2">Bij ieder bestelbaar werk vermelden we de belangrijkste kenmerken, prijs, beschikbaarheid en mogelijkheden voor ontvangst. Kennelijke vergissingen binden ons niet. Zolang de winkel als “binnenkort bestelbaar” staat en betalen is uitgeschakeld, kan via de website nog geen koopovereenkomst tot stand komen. Na opening ontstaat de overeenkomst wanneer de bestelling is aanvaard en elektronisch is bevestigd, onder voorbehoud van een aantoonbaar voorraadconflict.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Handgemaakt en uniek</h2><p className="mt-2">De werken worden met de hand gemaakt. Kleine onregelmatigheden, sporen van het materiaal en beperkte kleurverschillen horen bij hun karakter. Kleuren kunnen per beeldscherm afwijken. Zulke natuurlijke verschillen doen niets af aan de wettelijke rechten wanneer een werk niet aan de overeenkomst beantwoordt.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Prijzen en betaling</h2><p className="mt-2">Prijzen worden in euro vermeld. De definitieve btw-vermelding wordt vóór opening van de webshop toegevoegd zodra de btw-status is bevestigd. Eventuele ontvangst- of verzendkosten worden vóór het plaatsen van een bestelling afzonderlijk getoond. Online betalingen en donaties zijn momenteel uitgeschakeld; de voorwaarden voor de latere betaalmethode worden vóór activering zichtbaar gemaakt.</p></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Afhalen en levering</h2><div className="mt-2 space-y-2"><p>Je kunt gratis afhalen op afspraak aan het vestigingsadres in IJzendoorn. We nemen na een bevestigde bestelling persoonlijk contact op om een geschikt moment af te spreken. Afhalen is doorgaans mogelijk binnen twee tot vijf werkdagen.</p><p>Verzending binnen Nederland kost €6,95 per volledige bestelling, ongeacht het aantal of formaat van de gekozen werken. Als een afgesproken termijn niet haalbaar blijkt, informeren we de koper zo snel mogelijk en blijven de wettelijke rechten bij te late levering gelden.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Bedenktijd en retourneren</h2><div className="mt-2 space-y-2"><p>Bij een online aankoop heeft een consument in beginsel veertien dagen bedenktijd vanaf de dag na ontvangst. Binnen die termijn kan de overeenkomst zonder reden worden herroepen via de <a className="underline underline-offset-4" href="/herroepen">digitale herroepingsfunctie</a> of via <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}?subject=Herroeping%20bestelling`}>{siteDetails.email}</a>.</p><p>Na de herroeping moet het werk binnen veertien dagen worden teruggebracht of zorgvuldig worden teruggestuurd naar het bovenstaande Nederlandse adres. De rechtstreekse retourkosten zijn voor de koper als vooraf duidelijk is gemaakt wat die wijze van retourneren kost. Gebruik en verpakking mogen niet verder gaan dan nodig is om aard, kenmerken en werking te beoordelen; aantoonbare waardevermindering door verdergaand gebruik kan worden verrekend.</p><p>Bij volledige herroeping betalen we het aankoopbedrag en de kosten van de goedkoopste aangeboden standaardlevering binnen veertien dagen terug via hetzelfde betaalmiddel. We mogen wachten totdat het werk is ontvangen of bewijs van terugzending is geleverd. Bij gedeeltelijke herroeping worden oorspronkelijke leveringskosten niet terugbetaald.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Conformiteit en klachten</h2><div className="mt-2 space-y-2"><p>Een werk moet beantwoorden aan wat de koper op grond van de overeenkomst redelijkerwijs mag verwachten. Wettelijke garantierechten worden niet beperkt door deze voorwaarden.</p><p>Een klacht kan met bestelnummer en een duidelijke omschrijving worden gestuurd naar <a className="underline underline-offset-4" href={`mailto:${siteDetails.email}`}>{siteDetails.email}</a>. We bevestigen ontvangst en streven ernaar binnen veertien dagen inhoudelijk te reageren. Als meer tijd nodig is, laten we binnen die termijn weten wanneer een antwoord volgt.</p></div></section>
          <section><h2 className="font-semibold uppercase tracking-[0.12em]">Aansprakelijkheid en recht</h2><p className="mt-2">Niets in deze voorwaarden sluit aansprakelijkheid uit die volgens dwingend consumentenrecht niet mag worden uitgesloten. Op de overeenkomst is Nederlands recht van toepassing. Een consument behoudt de bescherming van dwingend recht van het land waar die woont. Geschillen kunnen worden voorgelegd aan de bevoegde rechter.</p></section>
        </>}
      </div>
    </article>
  )
}

export default LegalPage
