import type { EditorialZone } from '../data/editorialZones'

const InteractionPlaceholder = ({ type }: { type: EditorialZone['interactionType'] }) => {
  if (type === 'field') return <div className="relative h-36 overflow-hidden rounded-xl bg-[#c7b99e]/40">{[18, 34, 52, 71, 86].map((left, index) => <span key={left} className="absolute h-3 w-3 rounded-full border border-[#9b7d4f] bg-[#f3efe6]" style={{ left: `${left}%`, top: `${25 + (index % 3) * 22}%` }} />)}<span className="absolute inset-x-0 bottom-5 h-px bg-[#9b7d4f]/40" /></div>
  if (type === 'dream') return <div className="relative h-36 overflow-hidden rounded-xl bg-[radial-gradient(circle_at_30%_40%,rgba(181,154,190,.55),transparent_28%),radial-gradient(circle_at_72%_60%,rgba(124,162,174,.45),transparent_30%),#e8dfd2]"><span className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-[10px] uppercase tracking-[0.2em] text-neutral-600">beeld · kleur · gevoel</span></div>
  if (type === 'thread') return <div className="flex h-36 items-center justify-between overflow-hidden rounded-xl bg-white/25 px-6">{['kiezen', 'beginnen', 'herhalen', 'loslaten'].map((step, index) => <div key={step} className="relative z-10 flex flex-col items-center gap-3"><span className="h-4 w-4 rounded-full border border-[#9b7d4f] bg-[#f3efe6]" /><span className="hidden text-[8px] uppercase tracking-[0.13em] sm:block">{step}</span>{index < 3 && <span className="absolute left-1/2 top-2 -z-10 h-px w-[calc((100vw-10rem)/4)] bg-[#9b7d4f]/45" />}</div>)}</div>
  if (type === 'ritual') return <div className="grid h-36 grid-cols-4 gap-2">{['zitten', 'maken', 'kijken', 'geven'].map((step, index) => <div key={step} className="flex flex-col items-center justify-center rounded-xl bg-white/25"><span className="font-serif text-xl text-[#9b7d4f]">0{index + 1}</span><span className="mt-2 text-[8px] uppercase tracking-[0.13em]">{step}</span></div>)}</div>
  if (type === 'silence') return <div className="flex h-36 items-center justify-center rounded-xl bg-white/20"><span className="h-16 w-16 animate-pulse rounded-full border border-[#9b7d4f]/60" /><span className="absolute text-[8px] uppercase tracking-[0.18em] text-neutral-500">adem</span></div>
  return <div className="flex h-36 items-center justify-center gap-5 rounded-xl bg-white/20">{[1, 2, 3, 4, 5, 6].map((item) => <span key={item} className="h-9 w-9 rounded-full border border-[#9b7d4f]/50 bg-[#f3efe6]/50" />)}</div>
}

const EditorialZoneLayout = ({ content, continuation = false }: { content: EditorialZone; continuation?: boolean }) => (
  <article className={`overflow-hidden rounded-2xl bg-[#ded2bd] shadow-soft ring-1 ring-neutral-200/40 ${continuation ? 'mt-6' : ''}`}>
    <header className="grid gap-8 p-7 md:grid-cols-[minmax(0,1fr)_minmax(280px,.9fr)] md:items-center md:p-12">
      <div><p className="text-[10px] uppercase tracking-[0.22em] text-neutral-500">{content.eyebrow}</p><h1 className="mt-3 text-3xl font-semibold uppercase tracking-[0.17em]">{content.title}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-neutral-700">{content.coreLine}</p><p className="mt-5 max-w-xl text-sm leading-7 text-neutral-600">{content.introduction}</p><p className="mt-6 text-[10px] uppercase tracking-[0.16em] text-neutral-500">{content.question}</p></div>
      <img src={content.heroImage} alt={content.heroAlt} loading={continuation ? 'lazy' : 'eager'} className="aspect-[4/3] h-full max-h-96 w-full rounded-xl object-cover shadow-soft" />
    </header>

    <section className="border-t border-neutral-800/10 p-7 md:p-12" aria-labelledby={`${content.interactionType}-chapters`}><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.2em] text-neutral-500">Drie hoofdstukken</p><h2 id={`${content.interactionType}-chapters`} className="mt-2 text-lg font-semibold uppercase tracking-[0.14em]">Ruimte voor het verhaal</h2></div><span className="text-[9px] uppercase tracking-[0.14em] text-neutral-400">Inhoud volgt</span></div><div className="mt-7 grid gap-4 md:grid-cols-3">{content.chapters.map((chapter) => <section key={chapter.number} className="min-h-52 rounded-xl border border-white/45 bg-white/20 p-6"><span className="font-serif text-2xl text-[#9b7d4f]">{chapter.number}</span><h3 className="mt-7 text-sm font-semibold uppercase tracking-[0.14em]">{chapter.title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{chapter.prompt}</p><div className="mt-6 h-px w-8 bg-[#9b7d4f]/50" /></section>)}</div></section>

    <section className="grid border-t border-neutral-800/10 md:grid-cols-2"><div className="p-7 md:p-10"><p className="text-[10px] uppercase tracking-[0.2em] text-neutral-500">Luister</p><h2 className="mt-3 text-lg font-semibold uppercase tracking-[0.14em]">{content.audioLabel}</h2><div className="mt-6 flex items-center gap-4 rounded-full border border-neutral-800/15 bg-white/25 p-3"><button type="button" disabled aria-label="Audio volgt" className="flex h-10 w-10 cursor-not-allowed items-center justify-center rounded-full bg-neutral-900/35 text-white">▶</button><div className="h-px flex-1 bg-neutral-800/15"><div className="h-px w-0 bg-neutral-800" /></div><span className="text-[9px] uppercase tracking-[0.12em] text-neutral-400">volgt</span></div></div><div className="border-t border-neutral-800/10 p-7 md:border-l md:border-t-0 md:p-10"><p className="text-[10px] uppercase tracking-[0.2em] text-neutral-500">Ervaar</p><h2 className="mt-3 text-lg font-semibold uppercase tracking-[0.14em]">{content.interactionTitle}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{content.interactionText}</p><div className="relative mt-6"><InteractionPlaceholder type={content.interactionType} /></div></div></section>

    <section className="flex flex-col gap-5 border-t border-neutral-800/10 bg-white/15 p-7 sm:flex-row sm:items-center sm:justify-between md:p-10"><div><p className="text-[10px] uppercase tracking-[0.2em] text-neutral-500">Verbonden werk</p><h2 className="mt-2 text-lg font-semibold uppercase tracking-[0.14em]">{content.relatedProductTitle}</h2><p className="mt-2 text-sm text-neutral-600">Koppel hier later het persoonlijke verhaal aan het fysieke werk.</p></div><a href={`/werk/${content.relatedProductSlug}`} className="rounded-full border border-neutral-800/20 px-5 py-3 text-center text-[10px] uppercase tracking-[0.15em] hover:bg-white/35">Bekijk het werk →</a></section>
  </article>
)

export default EditorialZoneLayout
